name = "SerrePositivity"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["SerrePositivity"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
weak.linter.style.header = false # 著作権ヘッダは要求しない
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "master"

[[lean_lib]]
name = "SerrePositivity"
